// SPDX-License-Identifier: BSD-3-Clause-Clear
// GENERATED by gen_probe.py — do not edit.
pragma solidity 0.8.27;

// forgefmt: disable-start
import {FHE, ebool, euint8, euint64, externalEuint64} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";

contract ZamaProbe is ZamaEthereumConfig {
    euint64 internal a;
    euint64 internal b;
    euint64 internal c;
    euint64 internal d;
    euint8 internal sa;
    euint8 internal sb;
    ebool internal ea;
    ebool internal eb;

    /// Creates the operands, persistently allowed to this contract.
    function setup() external {
        a = FHE.asEuint64(uint64(7929944449538922630));
        FHE.allowThis(a);
        b = FHE.asEuint64(uint64(11813073661885085395));
        FHE.allowThis(b);
        c = FHE.asEuint64(uint64(18001080443617609857));
        FHE.allowThis(c);
        d = FHE.asEuint64(uint64(9827339105640753821));
        FHE.allowThis(d);
        // Casts of fresh euint64 values: an euint8 trivial handle has only 256 values and may be shared.
        sa = FHE.asEuint8(b);
        sb = FHE.asEuint8(d);
        // Conditions come from comparisons no row makes (rows put a or c first).
        ea = FHE.lt(b, d);
        eb = FHE.gt(d, b);
        FHE.allowThis(sa);
        FHE.allowThis(sb);
        FHE.allowThis(ea);
        FHE.allowThis(eb);
    }

    function rowSpecs() external pure returns (string[] memory ids, string[] memory fns, uint8[] memory kinds) {
        ids = new string[](32);
        fns = new string[](32);
        kinds = new uint8[](32);
        ids[0] = "add"; fns[0] = "r_add"; kinds[0] = 0;
        ids[1] = "sub"; fns[1] = "r_sub"; kinds[1] = 0;
        ids[2] = "mul"; fns[2] = "r_mul"; kinds[2] = 0;
        ids[3] = "min"; fns[3] = "r_min"; kinds[3] = 0;
        ids[4] = "max"; fns[4] = "r_max"; kinds[4] = 0;
        ids[5] = "square"; fns[5] = "r_square"; kinds[5] = 0;
        ids[6] = "eq"; fns[6] = "r_eq"; kinds[6] = 0;
        ids[7] = "ne"; fns[7] = "r_ne"; kinds[7] = 0;
        ids[8] = "lt"; fns[8] = "r_lt"; kinds[8] = 0;
        ids[9] = "lte"; fns[9] = "r_lte"; kinds[9] = 0;
        ids[10] = "gt"; fns[10] = "r_gt"; kinds[10] = 0;
        ids[11] = "gte"; fns[11] = "r_gte"; kinds[11] = 0;
        ids[12] = "and"; fns[12] = "r_and"; kinds[12] = 0;
        ids[13] = "or"; fns[13] = "r_or"; kinds[13] = 0;
        ids[14] = "xor"; fns[14] = "r_xor"; kinds[14] = 0;
        ids[15] = "not"; fns[15] = "r_not"; kinds[15] = 0;
        ids[16] = "shl"; fns[16] = "r_shl"; kinds[16] = 0;
        ids[17] = "shr"; fns[17] = "r_shr"; kinds[17] = 0;
        ids[18] = "rol"; fns[18] = "r_rol"; kinds[18] = 0;
        ids[19] = "ror"; fns[19] = "r_ror"; kinds[19] = 0;
        ids[20] = "select"; fns[20] = "r_select"; kinds[20] = 0;
        ids[21] = "trivial"; fns[21] = "r_trivial"; kinds[21] = 0;
        ids[22] = "input"; fns[22] = "r_input"; kinds[22] = 1;
        ids[23] = "random"; fns[23] = "r_random"; kinds[23] = 0;
        ids[24] = "allow"; fns[24] = "r_allow"; kinds[24] = 0;
        ids[25] = "allowThis"; fns[25] = "r_allowThis"; kinds[25] = 0;
        ids[26] = "allowTransient"; fns[26] = "r_allowTransient"; kinds[26] = 0;
        ids[27] = "allowPublic"; fns[27] = "r_allowPublic"; kinds[27] = 0;
        ids[28] = "isAllowed"; fns[28] = "r_isAllowed"; kinds[28] = 0;
        ids[29] = "div (plaintext divisor)"; fns[29] = "r_div__plaintext_divisor_"; kinds[29] = 0;
        ids[30] = "rem (plaintext divisor)"; fns[30] = "r_rem__plaintext_divisor_"; kinds[30] = 0;
        ids[31] = "add (plaintext operand)"; fns[31] = "r_add__plaintext_operand_"; kinds[31] = 0;
    }

    function r_add(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.add(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.add(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_sub(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.sub(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.sub(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_mul(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.mul(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.mul(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_min(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.min(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.min(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_max(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.max(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.max(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_square(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.mul(x, x);
        first = g - gasleft();
        g = gasleft();
        FHE.mul(z, z);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_eq(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.eq(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.eq(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_ne(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.ne(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.ne(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_lt(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.lt(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.lt(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_lte(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.le(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.le(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_gt(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.gt(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.gt(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_gte(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.ge(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.ge(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_and(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.and(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.and(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_or(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.or(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.or(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_xor(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.xor(x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.xor(z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_not(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.not(x);
        first = g - gasleft();
        g = gasleft();
        FHE.not(z);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_shl(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        euint8 s1 = sa;
        euint8 s2 = sb;
        uint256 g = gasleft();
        FHE.shl(x, s1);
        first = g - gasleft();
        g = gasleft();
        FHE.shl(z, s2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_shr(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        euint8 s1 = sa;
        euint8 s2 = sb;
        uint256 g = gasleft();
        FHE.shr(x, s1);
        first = g - gasleft();
        g = gasleft();
        FHE.shr(z, s2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_rol(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        euint8 s1 = sa;
        euint8 s2 = sb;
        uint256 g = gasleft();
        FHE.rotl(x, s1);
        first = g - gasleft();
        g = gasleft();
        FHE.rotl(z, s2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_ror(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        euint8 s1 = sa;
        euint8 s2 = sb;
        uint256 g = gasleft();
        FHE.rotr(x, s1);
        first = g - gasleft();
        g = gasleft();
        FHE.rotr(z, s2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_select(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        ebool cond = ea;
        ebool cond2 = eb;
        uint256 g = gasleft();
        FHE.select(cond, x, y);
        first = g - gasleft();
        g = gasleft();
        FHE.select(cond2, z, w);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_trivial(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.asEuint64(uint64(11694354482918244004));
        first = g - gasleft();
        g = gasleft();
        FHE.asEuint64(uint64(12502863062582107917));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_input(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        (bytes32 h1, bytes memory p1, bytes32 h2, bytes memory p2) = abi.decode(args, (bytes32, bytes, bytes32, bytes));
        uint256 g = gasleft();
        FHE.fromExternal(externalEuint64.wrap(h1), p1);
        first = g - gasleft();
        g = gasleft();
        FHE.fromExternal(externalEuint64.wrap(h2), p2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_random(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.randEuint64();
        first = g - gasleft();
        g = gasleft();
        FHE.randEuint64();
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_allow(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.allow(x, address(0xA11CE));
        first = g - gasleft();
        g = gasleft();
        FHE.allow(z, address(0xA11CE));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_allowThis(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        euint64 f1 = FHE.add(x, y);
        euint64 f2 = FHE.add(z, w);
        uint256 g = gasleft();
        FHE.allowThis(f1);
        first = g - gasleft();
        g = gasleft();
        FHE.allowThis(f2);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_allowTransient(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.allowTransient(x, address(0xA11CE));
        first = g - gasleft();
        g = gasleft();
        FHE.allowTransient(z, address(0xA11CE));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_allowPublic(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.makePubliclyDecryptable(x);
        first = g - gasleft();
        g = gasleft();
        FHE.makePubliclyDecryptable(y);
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_isAllowed(bytes calldata args) external view returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.isAllowed(x, address(0xA11CE));
        first = g - gasleft();
        g = gasleft();
        FHE.isAllowed(z, address(0xA11CE));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_div__plaintext_divisor_(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.div(x, uint64(7));
        first = g - gasleft();
        g = gasleft();
        FHE.div(z, uint64(9));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_rem__plaintext_divisor_(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.rem(x, uint64(7));
        first = g - gasleft();
        g = gasleft();
        FHE.rem(z, uint64(9));
        extra = g - gasleft();
        (x, y, z, w);
    }

    function r_add__plaintext_operand_(bytes calldata args) external returns (uint256 first, uint256 extra) {
        (args, first, extra);
        euint64 x = a;
        euint64 y = b;
        euint64 z = c;
        euint64 w = d;
        uint256 g = gasleft();
        FHE.add(x, uint64(7));
        first = g - gasleft();
        g = gasleft();
        FHE.add(z, uint64(9));
        extra = g - gasleft();
        (x, y, z, w);
    }
}
// forgefmt: disable-end
