import hre from "hardhat";
import { execTransactionThroughSafe, writeSafeBatch } from "../utils/safe";

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} must be set`);
  }
  return value;
}

/**
 * Accepts the pending default-admin transfer on the CommitmentRegistry as the Safe. With
 * SAFE_OWNER_KEY set it executes `acceptDefaultAdminTransfer()` through the Safe directly
 * (threshold-1 Safes only); without it - a real multisig, or an owner key that never leaves its
 * hardware - it writes a Transaction Builder batch to import into the Safe app, and doubles as
 * the verifier when re-run after it executes. Mirrors the host-chain `task:acceptAdminAsSafe`.
 */
async function main() {
  const { ethers } = hre;
  const registryAddress = ethers.getAddress(requireEnv("COMMITMENT_REGISTRY_ADDRESS"));
  const safeAddress = ethers.getAddress(requireEnv("SAFE_ADMIN_ADDRESS"));
  const ownerKey = process.env.SAFE_OWNER_KEY?.trim();
  const ownerSigner = ownerKey ? new ethers.Wallet(ownerKey, ethers.provider) : null;
  console.log(
    ownerSigner
      ? `Accepting as Safe ${safeAddress}, sending as owner ${ownerSigner.address}`
      : `SAFE_OWNER_KEY not set - writing a Safe batch file for ${safeAddress}`,
  );

  const registry = await ethers.getContractAt("CommitmentRegistry", registryAddress);
  const currentAdmin: string = await registry.defaultAdmin();
  if (currentAdmin.toLowerCase() === safeAddress.toLowerCase()) {
    console.log(`CommitmentRegistry (${registryAddress}): Safe is already the default admin`);
    return;
  }
  const [pendingAdmin, schedule] = await registry.pendingDefaultAdmin();
  if (pendingAdmin.toLowerCase() !== safeAddress.toLowerCase()) {
    throw new Error(
      `CommitmentRegistry (${registryAddress}): pending default admin is ${pendingAdmin}, not ` +
        `the Safe. Was the handover step of the deployment run?`,
    );
  }
  // OZ accepts only strictly after the schedule timestamp.
  const now = BigInt((await ethers.provider.getBlock("latest"))!.timestamp);
  const readyIn = now <= schedule ? schedule - now + 1n : 0n;
  const data = registry.interface.encodeFunctionData("acceptDefaultAdminTransfer");

  if (!ownerSigner) {
    const path = writeSafeBatch(hre, {
      safeAddress,
      slug: "accept-admin",
      name: "CoFHE - accept CommitmentRegistry default-admin transfer",
      description:
        `Accept the pending DEFAULT_ADMIN transfer on the CommitmentRegistry at ` +
        `${registryAddress}. Generated by scripts/acceptAdminAsSafe.ts.`,
      transactions: [{ to: registryAddress, data }],
    });
    console.log("\nWrote a Safe Transaction Builder batch:");
    console.log(`  ${path}`);
    console.log("Import it under Apps -> Transaction Builder in the Safe app, review, sign, execute.");
    // Printed as well as written, so the call can be reviewed without opening the file.
    console.log("\nThe transaction it contains:");
    console.log(`  CommitmentRegistry:`);
    console.log(`    to:    ${registryAddress}`);
    console.log(`    value: 0`);
    console.log(`    data:  ${data}`);
    if (readyIn > 0n) {
      // Collecting signatures can start before the delay passes; only execution must wait.
      console.log(`\nThe admin delay has not passed yet - execute after ~${readyIn}s (signing can start now).`);
    }
    console.log("Re-run this script after execution to verify - an accepted transfer is reported as done.");
    return;
  }

  if (readyIn > 0n) {
    throw new Error(
      `CommitmentRegistry (${registryAddress}): the admin delay has not passed - ` +
        `${readyIn}s to go. Re-run this script afterwards.`,
    );
  }
  await execTransactionThroughSafe(hre, safeAddress, ownerSigner, registryAddress, data);
  const newAdmin: string = await registry.defaultAdmin();
  if (newAdmin.toLowerCase() !== safeAddress.toLowerCase()) {
    throw new Error(`Accept executed but default admin is ${newAdmin}`);
  }
  console.log(`CommitmentRegistry (${registryAddress}): default admin is now the Safe`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
