import { config as dotenvConfig } from "dotenv";
import { resolve } from "path";
import { task } from "hardhat/config";
import chalk from "chalk";
import { HardhatRuntimeEnvironment } from "hardhat/types";

import { execTransactionThroughSafe, writeSafeBatch } from "../utils/safe";
import { resolveTaskManager } from "../utils/addressBook";

const dotenvConfigPath: string = process.env.DOTENV_CONFIG_PATH || "../.env";
dotenvConfig({ path: resolve(__dirname, dotenvConfigPath) });

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} must be set`);
  }
  return value;
}

/**
 * Decides who sends the deny-list change: the signer, or with `viaSafe` the Safe at
 * SAFE_ADMIN_ADDRESS. Either must hold ACCESS_LIST_MANAGER_ROLE.
 */
async function resolveAuthority(
  hre: HardhatRuntimeEnvironment,
  taskManager: any,
  viaSafe: boolean,
  taskName: string,
): Promise<
  { kind: "signer"; signer: any } | { kind: "safe"; safeAddress: string; ownerSigner: any | null }
> {
  const { ethers } = hre;
  const role = await taskManager.ACCESS_LIST_MANAGER_ROLE();

  if (!viaSafe) {
    const [signer] = await ethers.getSigners();
    if (!(await taskManager.hasRole(role, signer.address))) {
      throw new Error(
        `The signer (${signer.address}) does not hold ACCESS_LIST_MANAGER_ROLE on the TaskManager. ` +
          `After the handover use task:${taskName}AsSafe.`,
      );
    }
    return { kind: "signer", signer };
  }

  const safeAddress = ethers.getAddress(requireEnv("SAFE_ADMIN_ADDRESS"));
  if (!(await taskManager.hasRole(role, safeAddress))) {
    throw new Error(
      `Safe ${safeAddress} does not hold ACCESS_LIST_MANAGER_ROLE on the TaskManager. ` +
        `Was the handover step of the deployment run?`,
    );
  }
  const ownerKey = process.env.SAFE_OWNER_KEY?.trim();
  return {
    kind: "safe",
    safeAddress,
    ownerSigner: ownerKey ? new ethers.Wallet(ownerKey, ethers.provider) : null,
  };
}

/**
 * Adds accounts to (or removes them from) the TaskManager deny list.
 *
 * Idempotent: accounts already in the requested state are skipped, so a re-run after a Safe batch
 * executes verifies it. With `viaSafe` the same two paths as `task:setSignersAsSafe` apply: with
 * SAFE_OWNER_KEY the call is executed through the Safe (an EOA final admin sends directly),
 * otherwise one Transaction Builder batch is written.
 */
async function updateDenyList(
  hre: HardhatRuntimeEnvironment,
  rawAccounts: string,
  remove: boolean,
  viaSafe: boolean,
  out?: string,
) {
  const { ethers } = hre;
  const accounts = [...new Set(rawAccounts.split(",").map((a) => ethers.getAddress(a.trim())))];
  if (accounts.includes(ethers.ZeroAddress)) {
    throw new Error("refusing address(0) - the TaskManager rejects it.");
  }

  const tmAddress = await resolveTaskManager(hre);
  const taskManager: any = await ethers.getContractAt("TaskManager", tmAddress);
  console.log(chalk.dim(`TaskManager: ${tmAddress} on ${hre.network.name}`));
  if (await taskManager.accessListEnabled()) {
    console.log(chalk.yellow("The access list is enabled, so the deny list has no effect until it is disabled."));
  }

  const pending: string[] = [];
  for (const account of accounts) {
    if ((await taskManager.denyList(account)) !== remove) {
      console.log(chalk.green(`${account}: already ${remove ? "not denied" : "denied"} - nothing to do`));
      continue;
    }
    pending.push(account);
  }
  if (pending.length === 0) {
    return;
  }

  const taskName = remove ? "removeFromDenyList" : "addToDenyList";
  const call = `setDenyList([${pending.join(", ")}], ${!remove})`;
  const data = taskManager.interface.encodeFunctionData("setDenyList", [pending, !remove]);
  const authority = await resolveAuthority(hre, taskManager, viaSafe, taskName);

  if (authority.kind === "signer") {
    await (await taskManager.connect(authority.signer).setDenyList(pending, !remove)).wait();
  } else if (authority.ownerSigner) {
    console.log(
      chalk.green(`Executing through Safe ${authority.safeAddress} as owner ${authority.ownerSigner.address}`),
    );
    if (authority.ownerSigner.address.toLowerCase() === authority.safeAddress.toLowerCase()) {
      await (await authority.ownerSigner.sendTransaction({ to: tmAddress, data })).wait();
    } else {
      await execTransactionThroughSafe(hre, authority.safeAddress, authority.ownerSigner, tmAddress, data);
    }
  } else {
    const path = writeSafeBatch(hre, {
      safeAddress: authority.safeAddress,
      slug: remove ? "remove-from-deny-list" : "add-to-deny-list",
      name: `CoFHE - ${remove ? "remove from" : "add to"} TaskManager deny list`,
      description: `${call} on TaskManager ${tmAddress}. Generated by task:${taskName}AsSafe.`,
      transactions: [{ to: tmAddress, data }],
      outPath: out,
    });
    console.log(chalk.bold.blue("\nSAFE_OWNER_KEY not set - wrote a Safe Transaction Builder batch:"));
    console.log(`  ${path}`);
    console.log(`  ${call}`);
    console.log(`    to:    ${tmAddress}`);
    console.log(`    value: 0`);
    console.log(`    data:  ${data}`);
    console.log(
      chalk.yellow(
        "Import it in the Safe app under Apps -> Transaction Builder, review, sign and execute. " +
          "Re-run this task afterwards to verify.",
      ),
    );
    return;
  }

  for (const account of pending) {
    if ((await taskManager.denyList(account)) === remove) {
      throw new Error(`${account}: the transaction executed but denyList is still ${!remove}.`);
    }
    console.log(chalk.green(`${account}: ${remove ? "removed from" : "added to"} the deny list`));
  }
}

task("task:addToDenyList", "Block accounts from TaskManager task intake while the access list is disabled")
  .addParam("accounts", "Comma-separated addresses to deny")
  .setAction(async function (taskArguments, hre) {
    await updateDenyList(hre, taskArguments.accounts, false, false);
  });

task("task:removeFromDenyList", "Remove accounts from the TaskManager deny list")
  .addParam("accounts", "Comma-separated addresses to allow again")
  .setAction(async function (taskArguments, hre) {
    await updateDenyList(hre, taskArguments.accounts, true, false);
  });

task("task:addToDenyListAsSafe", "Add accounts to the TaskManager deny list through the Safe")
  .addParam("accounts", "Comma-separated addresses to deny")
  .addOptionalParam("out", "Path for the Safe batch file, when one is written")
  .setAction(async function (taskArguments, hre) {
    await updateDenyList(hre, taskArguments.accounts, false, true, taskArguments.out);
  });

task("task:removeFromDenyListAsSafe", "Remove accounts from the TaskManager deny list through the Safe")
  .addParam("accounts", "Comma-separated addresses to allow again")
  .addOptionalParam("out", "Path for the Safe batch file, when one is written")
  .setAction(async function (taskArguments, hre) {
    await updateDenyList(hre, taskArguments.accounts, true, true, taskArguments.out);
  });
