import chalk from "chalk";
import { task, types } from "hardhat/config";
import type { HardhatRuntimeEnvironment, TaskArguments } from "hardhat/types";
import { Contract, Wallet } from "ethers";
import { HardhatEthersSigner } from "@nomicfoundation/hardhat-ethers/signers";

import { resolveTaskManager } from "../utils/addressBook";
import { execTransactionThroughSafe, writeSafeBatch } from "../utils/safe";

const IMPLEMENTATION_SLOT = "0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc";

async function implementationOf(ethers: any, proxy: string): Promise<string> {
  return ethers.getAddress("0x" + (await ethers.provider.getStorage(proxy, IMPLEMENTATION_SLOT)).slice(-40));
}

/**
 * Whether the proxy already runs the pointer-based implementation, told by `share(acp, metadata)`
 * in its function dispatcher (`PUSH4 <selector>`); the first version has only `share(acp)`. The
 * code itself never equals the artifact: UUPSUpgradeable keeps the implementation's own address
 * as an immutable.
 */
async function runsPointerImplementation(ethers: any, proxy: string, Factory: any): Promise<boolean> {
  const selector: string = Factory.interface.getFunction("share").selector;
  const code: string = await ethers.provider.getCode(await implementationOf(ethers, proxy));
  return code.toLowerCase().includes("63" + selector.slice(2).toLowerCase());
}

/**
 * Who sends the upgrade: the signer when it holds UPGRADER_ROLE, otherwise the Safe at
 * SAFE_ADMIN_ADDRESS, which must hold it (the post-handover flow, as in task:upgradeTM).
 */
async function resolveSender(ethers: any, registry: any, signer: any): Promise<string | null> {
  const upgraderRole = await registry.UPGRADER_ROLE();
  if (await registry.hasRole(upgraderRole, signer.address)) return null;
  const rawSafe = process.env.SAFE_ADMIN_ADDRESS?.trim();
  if (!rawSafe) {
    throw new Error(
      `Refusing to upgrade ACPShareRegistry: the signer ${signer.address} lacks UPGRADER_ROLE and ` +
        `SAFE_ADMIN_ADDRESS is unset. Run as the upgrader, or set SAFE_ADMIN_ADDRESS to the Safe holding the role.`,
    );
  }
  const safe = ethers.getAddress(rawSafe);
  if (!(await registry.hasRole(upgraderRole, safe))) {
    throw new Error(`Refusing to upgrade ACPShareRegistry: ${safe} does not hold UPGRADER_ROLE.`);
  }
  return safe;
}

/**
 * Sends `upgradeToAndCall(impl, 0x)`: as the signer, through the Safe with SAFE_OWNER_KEY, or as
 * a Transaction Builder batch to import in the Safe app. True when it was sent from here.
 */
async function sendUpgrade(
  hre: HardhatRuntimeEnvironment,
  signer: any,
  safe: string | null,
  proxy: string,
  data: string,
): Promise<boolean> {
  const { ethers } = hre;
  if (safe === null) {
    await (await signer.sendTransaction({ to: proxy, data })).wait();
    console.log(chalk.green("Upgraded ACPShareRegistry"));
    return true;
  }

  const ownerKey = process.env.SAFE_OWNER_KEY?.trim();
  if (ownerKey) {
    const ownerSigner = new Wallet(ownerKey, ethers.provider);
    // An EOA final admin (testnets) sends directly: SAFE_OWNER_KEY is then its own key.
    if (ownerSigner.address.toLowerCase() === safe.toLowerCase()) {
      await (await ownerSigner.sendTransaction({ to: proxy, data })).wait();
    } else {
      await execTransactionThroughSafe(hre, safe, ownerSigner, proxy, data);
    }
    console.log(chalk.green(`Upgraded ACPShareRegistry as ${safe}`));
    return true;
  }

  const path = writeSafeBatch(hre, {
    safeAddress: safe,
    slug: "upgrade-share-registry",
    name: "CoFHE - upgrade ACPShareRegistry",
    description: `Upgrade the ACPShareRegistry proxy ${proxy} in place. Generated by task:upgradeShareRegistry.`,
    transactions: [{ to: proxy, data }],
  });
  console.log(chalk.bold.blue("\nWrote a Safe Transaction Builder batch:"));
  console.log(`  ${path}`);
  console.log(chalk.dim("Import it under Apps -> Transaction Builder in the Safe app, review, sign, execute."));
  console.log(`  to: ${proxy}\n  data: ${data}`);
  return false;
}

task("task:upgradeShareRegistry", "Upgrade the ACL's ACPShareRegistry in place to the pointer-based implementation")
  .addParam("key", "Signer key (default: the third configured account, as the other upgrade tasks)", "")
  .addParam("onlyvalidate", "Only validate the storage layout", false, types.boolean)
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { ethers, upgrades } = hre;
    const signer: HardhatEthersSigner =
      taskArguments.key === ""
        ? (await ethers.getSigners())[2]
        : (new Wallet(taskArguments.key).connect(ethers.provider) as unknown as HardhatEthersSigner);
    console.log(chalk.green("Network:", hre.network.name, "signer:", signer.address));

    const taskManagerAddress = await resolveTaskManager(hre);
    const taskManager: any = await ethers.getContractAt("TaskManager", taskManagerAddress);
    const acl: any = await ethers.getContractAt("ACL", await taskManager.acl());
    const proxy: string = await acl.shareRegistry();
    if (proxy === ethers.ZeroAddress) {
      throw new Error(`ACL ${await acl.getAddress()} serves no share registry (shareRegistry() is zero).`);
    }
    const oldImplementation = await implementationOf(ethers, proxy);
    console.log(chalk.green("TaskManager:", taskManagerAddress));
    console.log(chalk.green("ACPShareRegistry proxy:", proxy));
    console.log(chalk.green("Current implementation:", oldImplementation));

    const Factory = await ethers.getContractFactory("ACPShareRegistry");
    if (await runsPointerImplementation(ethers, proxy, Factory)) {
      console.log(chalk.green("The proxy already runs the pointer-based implementation. Nothing to do."));
      return;
    }

    // Import the layout the proxy runs now (the first version), then check this one against it.
    const V1 = await ethers.getContractFactory("ACPShareRegistryV1");
    await upgrades.forceImport(proxy, V1, { kind: "uups" });
    await upgrades.validateUpgrade(proxy, Factory, { kind: "uups" });
    console.log(chalk.green("✅ Storage layout is compatible with the first version"));
    if (taskArguments.onlyvalidate) return;

    const registry = Factory.attach(proxy) as Contract;
    const safe = await resolveSender(ethers, registry, signer);
    const implementation = await Factory.connect(signer).deploy();
    await implementation.waitForDeployment();
    const newImplementation = await implementation.getAddress();
    console.log(chalk.green("New implementation:", newImplementation));

    // The first version's shares are abandoned, not migrated: they stay in its storage, unread.
    const data = Factory.interface.encodeFunctionData("upgradeToAndCall", [newImplementation, "0x"]);
    if (await sendUpgrade(hre, signer, safe, proxy, data)) {
      const now = await implementationOf(ethers, proxy);
      console.log(chalk.green("Implementation now:", now));
      if (now === oldImplementation) console.log(chalk.red("WARNING: Implementation address did not change!"));
    }
  });
